# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  electronicsshopservice:
    image: electronicsshopservice
    build:
      context: .
      dockerfile: ElectronicsShop-service/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=ecommercedb;Uid=root;Pwd=2510203121
    
